version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build: .
    container_name: web
    ports:
      - "8000:8000"
    volumes:
      # Add volume for development hot-reload
      - .:/app
      - uploaded_files:/app/uploads
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_USER: root
      MONGO_PASS: example
      SECRET_KEY: "your-secret-key-here"  # Change this in production!

volumes:
  mongo_data:
  uploaded_files:
